# Site settings
title: 			Saquib Mian
email: 			saquib.mian@gmail.com
description: 	> # this means to ignore newlines until "baseurl:" 
 Software Developer. I read books and drink tea.

baseurl: 		"" # the subpath of your site, e.g. /blog/
url: 			"http://saquib.me" # the base hostname & protocol for your site

twitter_username: saquibmian
github_username:  saquibmian

# Build settings
markdown: kramdown
